### ISSUE TITLE
Complete list of documents needed for company

### ISSUE THREAD

**Issue by anujkhurana** [ajency/Compliance#2]
Coordinate with the CA and get complete list of documents needed.

PAN
TAN
Shop and establishment
PF registration
Any other?

**Comment by Tanvi-HR** [comment]
Pls review:

https://drive.google.com/open?id=1F550-h_VnuwJSbGq-IH9Y8TR62qWxkngSqPiWhzIcWo&authuser=0

**Comment by anujkhurana** [comment]
Looks good. Closing this issue. Please create a new issue for each document needed.
